# Generated by Django 5.0 on 2024-02-26 20:38

import colorfield.fields
import django.core.validators
import django.db.models.deletion
import djgeojson.fields
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dxf2Csv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dxf",
                    models.FileField(
                        max_length=200,
                        upload_to="uploads/djeocad/dxf/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["dxf"]
                            )
                        ],
                        verbose_name="DXF file",
                    ),
                ),
                (
                    "intro",
                    models.CharField(max_length=200, null=True, verbose_name="Notes"),
                ),
            ],
            options={
                "verbose_name": "DXF 2 CSV",
                "verbose_name_plural": "DXF 2 CSVs",
            },
        ),
        migrations.CreateModel(
            name="Drawing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Name of the drawing",
                        max_length=50,
                        verbose_name="Name",
                    ),
                ),
                (
                    "intro",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Description"
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "dxf",
                    models.FileField(
                        max_length=200,
                        upload_to="uploads/djeocad/dxf/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["dxf"]
                            )
                        ],
                        verbose_name="DXF file",
                    ),
                ),
                (
                    "geom",
                    djgeojson.fields.PointField(null=True, verbose_name="Location"),
                ),
                (
                    "designx",
                    models.FloatField(default=0, verbose_name="Design point X..."),
                ),
                ("designy", models.FloatField(default=0, verbose_name="...Y")),
                ("rotation", models.FloatField(default=0, verbose_name="Rotation")),
                (
                    "private",
                    models.BooleanField(default=False, verbose_name="Private drawing"),
                ),
                (
                    "needs_refresh",
                    models.BooleanField(
                        default=True,
                        editable=False,
                        verbose_name="Refresh DXF file from layers",
                    ),
                ),
                (
                    "epsg",
                    models.IntegerField(
                        editable=False, null=True, verbose_name="CRS code"
                    ),
                ),
                (
                    "fb_image",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drawing_image",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_drawing",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drawing",
                "verbose_name_plural": "Drawings",
            },
        ),
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Layer / block name"),
                ),
                (
                    "color_field",
                    colorfield.fields.ColorField(
                        default="#FFFFFF", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "linetype",
                    models.BooleanField(
                        default=True, verbose_name="Continuous linetype"
                    ),
                ),
                (
                    "geom",
                    djgeojson.fields.GeometryCollectionField(verbose_name="Entities"),
                ),
                (
                    "is_block",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Block definition"
                    ),
                ),
                (
                    "drawing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_layers",
                        to="djeocad.drawing",
                        verbose_name="Drawing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Layer",
                "verbose_name_plural": "Layers",
                "ordering": ("drawing", "name"),
            },
        ),
        migrations.CreateModel(
            name="Insertion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point", djgeojson.fields.PointField(verbose_name="Location")),
                ("rotation", models.FloatField(default=0, verbose_name="Rotation")),
                ("x_scale", models.FloatField(default=1, verbose_name="X scale")),
                ("y_scale", models.FloatField(default=1, verbose_name="Y scale")),
                (
                    "geom",
                    djgeojson.fields.GeometryCollectionField(
                        default=dict, verbose_name="Entities"
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="djeocad.layer",
                        verbose_name="Block",
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insertions",
                        to="djeocad.layer",
                        verbose_name="Layer",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
        migrations.AddConstraint(
            model_name="layer",
            constraint=models.UniqueConstraint(
                fields=("drawing", "name"), name="unique_layer_name"
            ),
        ),
    ]
