# Generated by Django 4.1.1 on 2022-10-19 17:11

import django.core.validators
import django.db.models.deletion
import djgeojson.fields
import filebrowser.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Drawing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Name of the building plan",
                        max_length=50,
                        verbose_name="Name",
                    ),
                ),
                (
                    "intro",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "fb_image",
                    filebrowser.fields.FileBrowseField(
                        max_length=200, null=True, verbose_name="Image"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=200,
                        null=True,
                        upload_to="uploads/images/drawing/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "dxf",
                    models.FileField(
                        max_length=200,
                        upload_to="uploads/djeocad/dxf/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["dxf"]
                            )
                        ],
                        verbose_name="DXF file",
                    ),
                ),
                ("geom", djgeojson.fields.PointField(verbose_name="Location")),
                ("rotation", models.FloatField(default=0, verbose_name="Rotation")),
                (
                    "private",
                    models.BooleanField(default=False, verbose_name="Private drawing"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_drawing",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
        ),
    ]
