# Generated by Django 4.1.1 on 2022-10-21 16:54

import colorfield.fields
import django.db.models.deletion
import djgeojson.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djeocad", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="drawing",
            options={"verbose_name": "Drawing", "verbose_name_plural": "Drawings"},
        ),
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Layer name")),
                (
                    "color_field",
                    colorfield.fields.ColorField(
                        default="#FF0000", image_field=None, max_length=18, samples=None
                    ),
                ),
                (
                    "geom",
                    djgeojson.fields.GeometryCollectionField(verbose_name="Elements"),
                ),
                (
                    "drawing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drawing_layer",
                        to="djeocad.drawing",
                        verbose_name="Drawing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Layer",
                "verbose_name_plural": "Layers",
            },
        ),
    ]
