# Generated by Django 4.1.1 on 2022-11-11 17:27

import django.db.models.deletion
import djgeojson.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djeocad", "0003_drawing_needs_refresh_alter_drawing_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="block",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Block definition"
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="drawing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_layers",
                to="djeocad.drawing",
                verbose_name="Drawing",
            ),
        ),
        migrations.CreateModel(
            name="Insertion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geom", djgeojson.fields.PointField(verbose_name="Location")),
                ("rotation", models.FloatField(default=0, verbose_name="Rotation")),
                ("x_scale", models.FloatField(default=1, verbose_name="X scale")),
                ("y_scale", models.FloatField(default=1, verbose_name="Y scale")),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="djeocad.layer",
                        verbose_name="Block",
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insertions",
                        to="djeocad.layer",
                        verbose_name="Layer",
                    ),
                ),
            ],
        ),
    ]
