# Generated by Django 4.1.1 on 2022-11-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djeocad", "0004_layer_block_alter_layer_drawing_insertion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="layer",
            old_name="block",
            new_name="is_block",
        ),
    ]
