# Generated by Django 4.1.1 on 2022-11-13 22:24

import colorfield.fields
import djgeojson.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djeocad", "0005_rename_block_layer_is_block"),
    ]

    operations = [
        migrations.RenameField(
            model_name="insertion",
            old_name="geom",
            new_name="point",
        ),
        migrations.AlterField(
            model_name="layer",
            name="color_field",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=18, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="geom",
            field=djgeojson.fields.GeometryCollectionField(verbose_name="Entities"),
        ),
        migrations.AlterField(
            model_name="layer",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Layer / block name"),
        ),
    ]
