# Generated by Django 4.1.1 on 2022-11-13 22:31

import djgeojson.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "djeocad",
            "0006_rename_geom_insertion_point_alter_layer_color_field_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="insertion",
            name="geom",
            field=djgeojson.fields.GeometryCollectionField(
                default={}, verbose_name="Entities"
            ),
        ),
    ]
