# Generated by Django 4.1.1 on 2022-11-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djeocad", "0008_rename_geom_insertion_block_geom_alter_drawing_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="insertion",
            old_name="point",
            new_name="geom",
        ),
    ]
