# Generated by Django 4.1.1 on 2022-11-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djeocad", "0009_rename_point_insertion_geom"),
    ]

    operations = [
        migrations.RenameField(
            model_name="insertion",
            old_name="geom",
            new_name="point",
        ),
    ]
