# Generated by Django 4.1.1 on 2022-11-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djeocad", "0010_rename_geom_insertion_point"),
    ]

    operations = [
        migrations.RenameField(
            model_name="insertion",
            old_name="block_geom",
            new_name="geom",
        ),
    ]
