# Generated by Django 4.1.1 on 2022-11-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djeocad", "0011_rename_block_geom_insertion_geom"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="layer",
            options={
                "ordering": ("name",),
                "verbose_name": "Layer",
                "verbose_name_plural": "Layers",
            },
        ),
        migrations.AddConstraint(
            model_name="layer",
            constraint=models.UniqueConstraint(
                fields=("drawing", "name"), name="unique_layer_name"
            ),
        ),
    ]
