# Generated by Django 4.1.1 on 2022-12-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djeocad", "0012_alter_layer_options_layer_unique_layer_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="insertion",
            options={"ordering": ("-id",)},
        ),
        migrations.AddField(
            model_name="drawing",
            name="epsg",
            field=models.IntegerField(
                editable=False, null=True, verbose_name="CRS code"
            ),
        ),
    ]
