# Generated by Django 4.1.1 on 2022-12-07 18:01

import djgeojson.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djeocad", "0013_alter_insertion_options_drawing_epsg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawing",
            name="geom",
            field=djgeojson.fields.PointField(null=True, verbose_name="Location"),
        ),
    ]
