# Generated by Django 4.1.1 on 2022-12-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djeocad", "0014_alter_drawing_geom"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="layer",
            options={
                "ordering": ("drawing", "name"),
                "verbose_name": "Layer",
                "verbose_name_plural": "Layers",
            },
        ),
        migrations.AddField(
            model_name="layer",
            name="linetype",
            field=models.BooleanField(default=True, verbose_name="Continuous linetype"),
        ),
    ]
