# Generated by Django 4.1.1 on 2023-06-29 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djeocad", "0016_drawing_designx_drawing_designy_alter_insertion_geom"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dxf2Csv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dxf",
                    models.FileField(
                        max_length=200,
                        upload_to="uploads/djeocad/dxf/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["dxf"]
                            )
                        ],
                        verbose_name="DXF file",
                    ),
                ),
                (
                    "intro",
                    models.CharField(max_length=200, null=True, verbose_name="Notes"),
                ),
            ],
            options={
                "verbose_name": "DXF 2 CSV",
                "verbose_name_plural": "DXF 2 CSVs",
            },
        ),
    ]
